### ISSUE TITLE
Code release?

### ISSUE THREAD

**Issue by GuptaSonam** [Youncy-Hu/MAGE#1]
Hi,

Interesting Work. When are you planning to release the training code?

Thanks, 
Sonam

**Comment by Youncy-Hu** [comment]
Hi, we are reorganizing the code and will release it in two weeks. Thanks.

**Comment by Youncy-Hu** [comment]
code has been uploaded.

**Comment by spacewalkingninja** [comment]
Hello, the model is still not here, I mark this as UN-Completed and UN-Closed.

**Comment by spacewalkingninja** [comment]
@Youncy-Hu - pls provide model "asap" (I need it for like within 6hrs thats when Im at home and will be programming. Tks!)
