### ISSUE TITLE
Youncy, where is the pretrained model? 

### ISSUE THREAD

**Issue by spacewalkingninja** [Youncy-Hu/MAGE#4]
Hello @Youncy-Hu I need the pretrained model. You are tasked to upload it here, provide a link and a detailed description of how to use it.
Thanks. 
Any questions, please ask

**Comment by Youncy-Hu** [comment]
Pre-trained models have been provided.

**Comment by Sun-Happy-YKX** [comment]
hello, does the pretrained model you refer indicate the  "VQ-VAE" pretrain model? I execute the code, but a mistake occurs, that is, "NameError: name 'ckpt_path' is not defined". I wonder if I have met the same problem. Thanks.
