### ISSUE TITLE
CATER dataset

### ISSUE THREAD

**Issue by Sun-Happy-YKX** [Youncy-Hu/MAGE#6]
我根据您readme的指示下载了对应文件
![image](https://user-images.githubusercontent.com/50354191/236686196-f6353a13-ddd4-4f97-a97a-af7bc587d9fc.png)
但是我在jieya解压之后文件夹如下：
![image](https://user-images.githubusercontent.com/50354191/236686210-8cd6eba3-ffb5-4344-84bc-7773914751cd.png)
并没有找到对应的.lmdb文件（如MINST），但是我看dataset代码里面要求将文件转化为.lmdb的形式，请问一下我是哪里出错了，或者遗漏了什么操作。
![image](https://user-images.githubusercontent.com/50354191/236686251-4975deeb-1f84-4eee-bcbb-76f2713a0fc5.png)

**Comment by Sun-Happy-YKX** [comment]
请问一下您是否介意直接将CATER数据集对应的.lmdb直接分享一下，感谢您！

**Comment by Sun-Happy-YKX** [comment]
![image](https://user-images.githubusercontent.com/50354191/236686695-47025222-68e9-455a-bd0d-305aac197072.png)
执行代码报错如下

**Comment by Youncy-Hu** [comment]
Hi, I use an LMDB file to efficiently store all frames of the train/test set. To load the dataset for training vqvae, you can directly utilize "CATER" class to load the data and reshape the video array from [B, T, C, H, W] to [BxT, C, H, W]. Alternatively, you can convert the dataset into an LMDB file using the provided code snippets below:

```
import lmdb
import platform
import pickle
from decord import VideoReader

with open('../datasets/CATER-GEN-v1/train_explicit.json', 'r') as fp:
    anno = json.load(fp)
map_size = 1099511627776 * 2 if platform.system() == "Linux" else 1280000
db = lmdb.open(
    '../datasets/CATER-GEN-v1/vqvae_train.lmdb', map_size=map_size, subdir=False, meminit=False, map_async=True
)
INSTANCE_COUNTER: int = 0
txn = db.begin(write=True)
for idx in range(len(anno)):
    video_path = anno[str(idx)]['video']
    video_path = os.path.join('../datasets/CATER-GEN-v1', video_path)
    vid = VideoReader(video_path)
    frame_num = len(vid)
    images = vid.get_batch(list(range(frame_num))).asnumpy()
    for i in range(images.shape[0]):
        txn.put(
            f"{INSTANCE_COUNTER}".encode("ascii"),
            pickle.dumps(images[i], protocol=-1)
        )
        INSTANCE_COUNTER += 1
txn.commit()
db.sync()
db.close()
```
